- name: Get information about ansible control machine
  hosts: localhost
  gather_facts: yes

- hosts: all
  gather_facts: no
  tasks:
    - name: ensure that localhost is not skipped
      assert:
        that:
          - '"ansible_hostname" in hostvars.localhost'
        msg:
          - Hostvars from localhost are required to run some tasks.
          - Make sure to include localhost when using --limit.

- name: Setup password store
  hosts: all

  vars:
    pass_gpg_key_fingerprint: "EC5E 11DD EF42 BF79 FBFA 4F4E FF6A DDEB B33A 5D2F" 
    key_filename: "GPG_key_{{ pass_gpg_key_fingerprint | replace(' ', '') }}.asc"
    control_machine_name: "{{ hostvars.localhost.ansible_hostname }}"
    control_machine_address: "{{ control_machine_name }}.local"
    hide_sensitive_logs: false
    gpg_sync_dir: "{{ ansible_env.HOME }}/.gnupg/sync"

  roles:
    - known-hosts

  tasks:

    - name: install apt packages
      apt:
        name:
          - expect  # for automatic ssh key unlocking
          - gnupg2  # I want to be able to use gpg2 command for compatibility
          - git
          - xclip  # for putting password in clipboard
          - pass
          - pinentry-tty  # for unlocking keys in agent without gui
          - pwgen  # password generator
      become: yes

    - name: ensure directories exist
      file:
        dest: "{{ ansible_env.HOME }}/{{ item }}"
        state: directory
        mode: 0700
      loop:
        - .ssh
        - .ssh/keys
        - .gnupg
        - .gnupg/sync

    # - name: copy GPG key for password store
    #   copy:
    #     dest: "{{ ansible_env.HOME }}/.gnupg/{{ key_filename }}"
    #     content: "{{ lookup('passwordstore', 'misc/personal-gpg-key returnall=true') }}"
    #     mode: 0600
    #   no_log: "{{ hide_sensitive_logs }}"
    #   register: gpg_key_status

    - name: export gpg secret keys and revocation certs
      file:
        state: link
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - src: "{{ ansible_env.HOME }}/.gnupg/private-keys-v1.d"
          dest: "{{ gpg_sync_dir }}/private-keys"
        - src: "{{ ansible_env.HOME }}/.gnupg/openpgp-revocs.d"
          dest: "{{ gpg_sync_dir }}/revocation-certs"

    - name: export pubring
      shell: gpg2 --export --armor > "{{ gpg_sync_dir }}/pubring-{{ inventory_hostname }}.asc"

    - name: export ownertrust
      shell: gpg2 --export-ownertrust > "{{ gpg_sync_dir }}/ownertrust-{{ inventory_hostname }}"

    - name: sync data (two-way)
      synchronize:
        # trailing slash is important
        src: "{{ gpg_sync_dir }}/"
        dest: "{{ gpg_sync_dir }}/"
        mode: "{{ item }}"
      loop:
        - push
        # - pull
      tags: sync

    - meta: end_play

    # - name: sync pubring and ownertrust (one-way)
    #   copy:
    #     src: "{{ item.src }}"
    #     dest: "{{ item.dest }}"
    #   loop:
    #     - src: "{{ hostvars.localhost.ansible_env.HOME }}/.gnupg/pubring-export.asc"
    #       dest: "{{ ansible_env.HOME }}/.gnupg/pubring-import.asc"
    #     - src: "{{ hostvars.localhost.ansible_env.HOME }}/.gnupg/ownertrust-export"
    #       dest: "{{ ansible_env.HOME }}/.gnupg/ownertrust-import"

    # - name: import gpg key
    #   command: gpg2 --batch --import {{ ansible_env.HOME }}/.gnupg/{{ key_filename }}
    #   when: gpg_key_status.changed

    - name: import pubring
      shell: gpg2 --import {{ gpg_sync_dir }}/pubring-*.asc

    - name: import ownertrust
      shell: gpg2 --import-ownertrust {{ gpg_sync_dir }}/ownertrust-*

    - name: clone password store
      git:
        repo: git@bitbucket.org:jan-warchol/password-store.git
        dest: "{{ passwordstore_path }}"
        update: no  # "yes" can reset --hard unpushed commits
        recursive: no  # "offline" module requires special steps

    - name: configure git user email
      git_config:
        key: user.email
        value: jan.warchol@gmail.com
        repo: "{{ passwordstore_path }}"

    - name: clone special submodule with top-secret passwords
      git:
        accept_hostkey: yes  # low risk since it's over LAN
        # FIXME: passwordstore_path should be taken from control machine hostvars
        repo: jan@{{ control_machine_address }}:{{ passwordstore_path }}/offline
        dest: "{{ passwordstore_path }}/offline"
      # doesn't make sense to clone repo into itself
      when: inventory_hostname != control_machine_name

    - name: configure git user email
      git_config:
        key: user.email
        value: jan.warchol@gmail.com
        repo: "{{ passwordstore_path }}/offline"
